### PR TITLE
Add MIT License to Repository

### PR DESCRIPTION
**Pull request by sghill**
On [Google Code](http://code.google.com/p/android-binding/), this project is listed as having a MIT license. Without a `LICENSE` file checked into the repository, or it being mentioned in the `README`, it's hard to tell if it's still under the MIT license.

I'd gladly submit a pull request, but I'm unsure of who the copyright should belong to.

Thanks!

### CODE REVIEW

**Comment by gueei** [comment]
Yes, we still under MIT.

Is there any good way to automatically add those license stuff to source?

Andy

**Comment by sghill** [comment]
I can add a `LICENSE` file and do a pull request if you'd like. That'd be
pretty easy.

Copyright belongs to "Andy Tsui" or "AndroidBinding committers"?

**Comment by sghill** [comment]
Went with the more generic AndroidBinding committers because there are three committers on the Google Code project. Hope this helps!

**Comment by gueei** [comment]
Yes please.

Thanks.

**Comment by sghill** [comment]
Should be all set for the `Merge pull request` button. Thanks!

**Pull request merged**
